### ISSUE TITLE
ウォレットに関して注意書き

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-website#126]
iOSで
ログインループする可能性があること

iOS Chromeで
QRスキャンが使えないこと

iOS ホーム画面起動が
使えないことがあること

を書いておく必要がある

**Comment by ryuseikurata** [comment]
walletのアプリケーションでいう案件な気がしてきました。
corporateサイトでわざわざいうはずないような、、

**Comment by YuKimura45z** [comment]
起動できないアプリの中に起動できませんってかくの、

ジャイアンがのび太に言った
「返事できないんだったら言えよ」
と同じやと思う

**Comment by ryuseikurata** [comment]
でも、walletをコーポレートサイトから経由しないできた人にとっては不親切な気がします。
なので
- [ ] コーポレートサイトにも載せる
- [ ] walletは、ログインができないというところなので、ログイン前に見せるようにする

これが折衷案かなと

**Comment by YuKimura45z** [comment]
せやな

**Comment by Dragon-taro** [comment]
いつも通り俺がコンテンツを考えてデザインを野田さんにお願いしましょう

**Comment by Dragon-taro** [comment]
これはサイトとwalletの両方に同じコンテンツをのっけるって認識でおk？
コンテンツは俺が考えたらいいか。
優先順位はどうしましょう？

**Comment by YuKimura45z** [comment]
これ今日から動いてもらっていいすか？

**Comment by YuKimura45z** [comment]
ウォレットにはサイトへのリンクをはっておけばおｋなので
とりあえずサイトのウォレットページに

iOSで
ログインループする可能性があること

iOS Chromeで
QRスキャンが使えないこと

iOS ホーム画面起動が
使えないことがあること

**Comment by Dragon-taro** [comment]
ウォレットページに追記でokすか？

**Comment by YuKimura45z** [comment]
これもう終わった？

**Comment by YuKimura45z** [comment]
もしもーし

**Comment by Dragon-taro** [comment]
# Walletの注意
iOS端末に関して以下の挙動が確認されていますので、ご注意ください。
- ログインできない場合がある
- ホーム画面起動ができない場合がある
- ChromeでQRスキャンが使えない

一時的なエラーの場合は時間を開けてお試しください。
