### ISSUE TITLE
フォルダ構成整理

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-website#127]
フォルダ構成わちゃわちゃなってる。

・containersフォルダを廃止してcomponentsに統合
・aboutとcontactをcompany/about、company/contactに
・faqとsubsidyをpegged-asset/faq、pegged-asset/subsidyに
・privacy-policyをterms/privacy-policy（ウォレットと同じ）

すると整理されるんじゃないでしょうか

**Comment by YuKimura45z** [comment]
stable-coinではなくpegged-assetとしているのは

ステーブルコインというのはマーケットに合わせた呼称なだけで厳密には正しくないと思ってるから。

digital-legal-currencyとかでもまあいいとおもうが
stable-coin呼称はブロックチェーン業界内にしか効かず、マスアダプションにあたっては障害になると思う

長期目線で

**Comment by YuKimura45z** [comment]
pegged assetは業界外どうせわからないので
digital-legal-currencyのほうがいいのかもしれない

**Comment by Dragon-taro** [comment]
components以下の整理もしたい。partsとmoduleぐらいに切り分けてもいい気がする 。
完全なアトミックにするほどのことでもない気はするが、もう少し細分化した方がわかりやすそう。

要検討
