### ISSUE TITLE
Sass化

### ISSUE THREAD

**Issue by Dragon-taro** [lcnem/lcnem-website#145]
別にやらなくても問題はないですが、シュレックとタケルさんの練習兼ねて各コンポーネントをSass化していきましょう。

それやる前にcssの規約を決めてもいいのかも？
BEM×Sassを試してみたい。

**Comment by YuKimura45z** [comment]
cssの規約に関してはあるタイプをリサーチチャンネルに貼ってもらわないと話は進められないと思う

ほかのissueと比較して優先順位は低めでやっていきましょう（いまからつくるやつはsassでいいとおもうが
