### ISSUE TITLE
ステーブルコイン専用ページ

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-website#158]
digital-legal-currency/フォルダ内にfaqとsubsidyができていて、subsidyをtopからリンクするのかfaqからリンクするのかイマイチ定まらない

そこでdigital-legal-currencyページを作り、それの子コンポーネントとしてFAQを表示
subsidyへはそこからリンク、でいいんじゃなかろうか

**Comment by ryuseikurata** [comment]
` digital-legal-currencyページを作る `　
賛成
