### ISSUE TITLE
メニュー開くと一番上にスクロールする問題

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-website#166]
原因はメニューがトップバナーと同じdivコンテナに入ってないことのような気がするが

どうすればいいか相談したい

**Comment by Dragon-taro** [comment]
スムーズなスクロールとのトレードオフで悩ましいですね、、

**Comment by Dragon-taro** [comment]
俺の勘違いかもしれないですが

**Comment by YuKimura45z** [comment]
すまん、スムーズなスクロールがなんたるかが把握できてない

**Comment by YuKimura45z** [comment]
appleのOSだけでのことは、優先順位としては低いとおもう
メニュー開くと上にいく違和感のほうがでかいのが個人的感想

**Comment by Dragon-taro** [comment]
これに関してはgoogleがゴミやからしゃーなしgoogleに合わせるってのが妥協案として確かに適切ですね
