### ISSUE TITLE
lcnemintページ

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-website#215]
- 日本初の実用向けCosmos SDK製Tendermintチェーンであること
- コンソーシアムコンセンサスであること
- 法人のコンソーシアムバリデータを募集していること
- Cosmosネットワークに参加するすべてのチェーンでLCNEM Chequeが使えること

アピール

**Comment by Dragon-taro** [comment]
Assigner is ダレ

**Comment by YuKimura45z** [comment]
4つは書いたけどすぐおわった
スペック
バリデータ…コンソーシアム
コンセンサスアルゴリズム…TendermintBFT
ブロック承認…確定的
ブロックタイム…10秒（にconfig設定しよう）

とかもかいとくか
あと案ある？
