### ISSUE TITLE
上のツールバー

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-website#233]
いま、サイドナビ、スプラッシュスクリーン的なのスクロールしてからみえるようになってるやんん、z indexの物理的に。
これ、1ミリでもすくろーるしたらフェードインで表示とかにしたほうがサイドナビへのアクセスしやすいんじゃないか？と思った

**Comment by YuKimura45z** [comment]
フェードイン・アウトはマテリアルデザインに反するので、少しでも下にスクロールしたら上からスライドインしてくるほうがよさそう。
これ、そろそろだれかやってみませんか。

**Comment by Dragon-taro** [comment]
それはちょっと思ってました
jsでスクロール関してclass名変更したらいけるんで誰か頼む🙏
