### ISSUE TITLE
ページ遷移時にページ上部に移動させる

### ISSUE THREAD

**Issue by Dragon-taro** [lcnem/lcnem-website#236]
前からそういや気になってた
スクロール関連調べててついでに出てきたからissueにしとく
http://neos21.hatenablog.com/entry/2018/07/21/080000

**Comment by Dragon-taro** [comment]
routerサービス作ってたらそこに書いてなかったらAppCompnetかな（中のコード忘れたw）

**Comment by YuKimura45z** [comment]
完了
