### ISSUE TITLE
[10/8]Facebook,Twitterシェアボタン

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-website#46]
* OGPつけるならあってもいいかなと。

**Comment by YuKimura45z** [comment]
問題が一つあって

angular、コンポーネント内のscriptタグは安全のため破棄しやがるんよね

なので埋め込みボタンが使えない


https://developers.google.com/web/updates/2016/09/navigator-share

web share api使ったほうが良さげ
