### ISSUE TITLE
[10/14以内]title, descriptionの整備

### ISSUE THREAD

**Issue by akinahiko** [lcnem/lcnem-website#48]
整備した方が良いかなと思いました。
（SEOというよりはUXの観点で）

※SEO観点だと「LCNEM」以外の検索ワードで検索に引っかからないような感じなのでそちらの対策もしたいところですが、body内が現状javascriptの読み込みタグのみでテキスト情報が出ないようなので、手をつけるとしたらまずはその辺りからですね。

**Comment by YuKimura45z** [comment]
Angularの制約でbodyタグになんか書くのはできないので、description整備する方向で行きましょう。
descriptionの文言さえ決まれば、もうプルリクいきましょう。

**Comment by akinahiko** [comment]
ありがとうございます。#49で先ほど上げたissueとの絡みもあるので、#49の方向性が決まったらサクッと文面作れればと思います。

**Comment by akinahiko** [comment]
下記、meta周りの原稿をご提案します。お手数をおかけ致しますが、ご確認よろしくお願い致します。（keywordsはあまり意味をなさないと思うので必須では無いのですが、念のため入れておきました。）

title
株式会社LCNEM

description
株式会社LCNEMは、ステーブルコイン、LCNEM WALLET、ちけっとピアツーピア、Payment Request APIといったブロックチェーンの技術を活用したプロダクトを通じて、これからのデジタル社会のための新しいコスト改善ソリューションをご提案します。

keywords
LCNEM,ステーブルコイン,LCNEM WALLET,ちけっとピアツーピア,Payment Request API,ブロックチェーン

**Comment by YuKimura45z** [comment]
完
