### ISSUE TITLE
arrow_backボタンについて

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-website#62]
toolbarのarrow_backボタン、現状はrouterLinkを指定しているが、
`(click)="history.back();"`のほうが良いのではという気がしてきた。

**Comment by ryuseikurata** [comment]
そうなんですか！

**Comment by YuKimura45z** [comment]
どのページから来たとしても、arrow_backおしたらhomeいってしまうやろ？
そやけどhistory.backやったら来たとこに戻れるし、なにより履歴が荒れない（いままでやと、homeにとんで、そこでブラウザで戻る押すと、arrowbackあるとこにもどってきて、ややこしい）

**Comment by YuKimura45z** [comment]
https://github.com/lcnem/lcnem-wallet/issues/95#issuecomment-427732895
これと同様でいける。
