### ISSUE TITLE
footerつけたい

### ISSUE THREAD

**Issue by Dragon-taro** [lcnem/lcnem-website#73]
コーポレートサイトならいるっしょ
あと、あった方がデザイン的にいい感じになると思われ
https://github.com/lcnem/lcnem-website/issues/69#issue-368030870 のfooterみたいな感じ？

**Comment by YuKimura45z** [comment]
賛成

**Comment by YuKimura45z** [comment]
- &copy; LCNEM, Inc.

以外につけるもんあるかしら

**Comment by akinahiko** [comment]
footerの件もよければ#49でデザインまとめるときにレイアウト提案させてもらいますね。

© LCNEM, Inc.

と、あとはハンバーガーに隠しているリンクは一通り入れておいても良いかなと思います。ハンバーガー開かない人も結構いますしね。

**Comment by Dragon-taro** [comment]
てか会社概要そんなに内容ないからfooterにつけてもいい説
でも、会社概要は流石にページとして必要か、、

**Comment by YuKimura45z** [comment]
完
