### ISSUE TITLE
アクセスした瞬間に見える情報の最適化

### ISSUE THREAD

**Issue by Dragon-taro** [lcnem/lcnem-website#93]
<img width="1431" alt="2018-10-16 14 09 43" src="https://user-images.githubusercontent.com/28052685/46993991-47ace400-d14d-11e8-9761-837842fc543c.png">
所見が文字が変な位置にきてて美しくない
一枚のスライドになるような感じにしたい（例えば下の説明まで見えるようにしておく）

**Comment by Dragon-taro** [comment]
上記の画像は現状のやつが下によってしまってるよね、ってことが言いたいです

**Comment by YuKimura45z** [comment]
たしかに。
toolbarの存在で100vhにするとちょっとはみ出てしまうというのがあるので
画像と文字を縦関係にしたままやるのは難儀な気がするので

なんかでかいバックグラウンドイメージつくってしまったほうがいいかもしれないね。

**Comment by Dragon-taro** [comment]
100vhまではtoolbarを消すってのも選択肢としてありですね
よくあるパターン

**Comment by YuKimura45z** [comment]
アリやなあ。
* 100vhまではtoolbar消す
* でかいバックグラウンドイメージつくる

**Comment by Dragon-taro** [comment]
topのリニューアルでやった
