### ISSUE TITLE
サイト全体のデザイン向上案

### ISSUE THREAD

**Issue by Dragon-taro** [lcnem/lcnem-website#95]
気になったところ
1. 全体的に余白が少ない
2. 単調
3. メニューボタン下なのが違和感
4. メディアリンクがわかりにくい

改善案
1. 余白（特にsection間）を多めにとる（mergin: 60px 0）ぐらいでよさそう
2. sectionの背景色を交互になるように並べると良さそう
3. 右のほうが良さそう
4. titleとディスクリプションとアイキャッチを取ってきて表示したい

それと、個別のプロダクトページを作るなら、各プロダクトはflexの横並びで画像＋簡単な説明＋リンクボタンとかで良さそう

イメージ↓
<img width="1197" alt="2018-10-16 15 32 21" src="https://user-images.githubusercontent.com/28052685/46996850-f7d41a00-d158-11e8-94ec-0c651997d3aa.png">

**Comment by YuKimura45z** [comment]
結局、個別のプロダクトページはつくらず、各プロダクトに説明ページ設けることに

**Comment by YuKimura45z** [comment]
余白賛成。
交互色賛成。
右にするかあ。
あー、OGPスクレイピングしちゃうということか？

**Comment by Dragon-taro** [comment]
今後のメディア露出を考えるとスクレイピングしたほうがいいんですけど、まあ２個やしコピペでいいでしょw
誰かの練習に使ってもいいですが

**Comment by Dragon-taro** [comment]
個別ページ作らないなら現状に余白持たせるで良さそう
